Home-work-4
YuliaLitvinenko/CodingGirls pull request #3
Opened 2018-03-19 20:20 UTC by YuliaLitvinenko

2018-03-20 21:04 UTC, Afelua requested changes

2018-03-20 21:04 UTC, Afelua commented on index4.html
> +          <article class="line-1">
Можно рассмотреть, что элемент строки в main - это - article. Но тогда внутрь article картинку тоже нужно помещать (article - однотипные элементы статьи, у нас они однотипны с картинкой вместе). Ошибки в этом не будет)

2018-03-20 21:04 UTC, Afelua commented on index4.html
> +      <div>
Здесь еще один div - родитель ul - лишний.

2018-03-20 21:04 UTC, Afelua commented on index4.html
> +        <div class="article-2">
Почему разные названия классов: article-1, article-2, у нас разве отличаются эти элементы?

2018-03-20 21:04 UTC, Afelua commented on index4.html
> +          <article class="line-2">
Аналогичный комментарий (line-1, line-2)

2018-03-20 21:04 UTC, Afelua commented on style.css
> +.main-nav-menu {
Также нужно убрать точки у меню.

2018-03-20 21:04 UTC, Afelua commented on index4.html
> +    <h1>Fitness in a can/</h1>
Задать цвет и др. свойства, сделать отступ слева и сверху. Для "Yes you can/" аналогично.

2018-03-20 21:04 UTC, Afelua commented on style.css
> +	background-size: contain;
Лучше сделать `background-size: cover;`, тогда изображение будет корректно по ширине на всех мониторах.

2018-03-20 21:04 UTC, Afelua commented on style.css
> +.main-info-container {
Здесь нужно отрегулировать отступ сверху через padding

2018-03-20 21:04 UTC, Afelua commented on style.css
> +.line-1 {
Задать стили для каждого подэлемента этого блока (It's all about, Fitness first и т.д.)

2018-03-20 21:04 UTC, Afelua commented on index4.html
> +          <img src="./images/img1.jpg" width="600">
Лучше задать высоту, а не ширину картинки, тогда она будет масштабироваться корректно.

2018-03-20 21:04 UTC, Afelua commented on index4.html
> +          <img src="./images/img2.jpg" width="600">
Лучше задать высоту, а не ширину картинки, тогда она будет масштабироваться корректно.

2018-03-20 21:04 UTC, Afelua commented on index4.html
> +<!DOCTYPE html>
Лучше всю верстку писать в файле index.html (без цифры)

2018-03-23 19:18 UTC, YuliaLitvinenko commented on index4.html
> +<!DOCTYPE html>
Ок!

2018-03-23 19:43 UTC, YuliaLitvinenko commented on index4.html
> +          <article class="line-1">
Поправила!

2018-03-23 19:56 UTC, YuliaLitvinenko commented on index4.html
> +      <div>
И точно! Убрала)

2018-03-25 09:09 UTC, YuliaLitvinenko commented on index4.html
> +        <div class="article-2">
Одинаковые) Поправила!

2018-03-25 09:09 UTC, YuliaLitvinenko commented on style.css
> +.main-nav-menu {
Убрала!)

2018-03-25 09:11 UTC, YuliaLitvinenko commented on style.css
> +	background-size: contain;
Поставила cover

2018-03-25 09:11 UTC, YuliaLitvinenko commented on style.css
> +.main-info-container {
Да, досмотрела 5 урок до этого момента и везде покопалась с отступами.

2018-03-25 09:11 UTC, YuliaLitvinenko commented on style.css
> +.line-1 {
Готово!

2018-03-25 09:15 UTC, YuliaLitvinenko commented on index4.html
> +          <img src="./images/img1.jpg" width="600">
О, точно! Я сначала не прочитала этот комментарий, и когда сама доделывала, задала и ширину и высоту. Интересно, что высота круче работает..

2018-03-25 20:12 UTC, Afelua approved these changes

2018-03-26 11:26 UTC, merged