Home-work-6
YuliaLitvinenko/CodingGirls pull request #4
Opened 2018-03-26 17:17 UTC by YuliaLitvinenko

2018-03-28 22:03 UTC, Afelua requested changes

2018-03-28 22:03 UTC, Afelua commented on style.css
> +  src: url("./fonts/OpenSans/OpenSans-Regular.ttf");
Одинаковый файл шрифта подключаете для Regular и Light

2018-03-28 22:03 UTC, Afelua commented on style.css
> +	width: 100px;
Для формы тоже давайте шрифты пропишем)

2018-03-28 22:03 UTC, Afelua commented on style.css
> +	height: 18px;
Нужно для каждой иконки соц. сети задать свои, актуальные именно для нее height и  width

2018-03-30 20:27 UTC, YuliaLitvinenko commented on style.css
> +  src: url("./fonts/OpenSans/OpenSans-Regular.ttf");
Ага, поправила. Я почему-то подумала, что если я напишу Font Weight 100, это Light и будет на выходе. А нет)

2018-03-30 20:27 UTC, YuliaLitvinenko commented on style.css
> +	width: 100px;
Готово!

2018-03-30 21:05 UTC, YuliaLitvinenko commented on style.css
> +	height: 18px;
Так, задала. Правда больше похожи на реальные они не стали...

2018-03-31 10:37 UTC, YuliaLitvinenko commented
Я поменяла в form и button размер шрифта, а то иначе форма и кнопка никак по размеру не совпадали - мистика какая-то. Кнопка вечно на пиксель больше и ее вниз куда-то тянет, она по каким-то другим правилам живет.

2018-04-01 20:09 UTC, Afelua approved these changes

2018-04-01 21:06 UTC, merged