Home work 7
YuliaLitvinenko/CodingGirls pull request #5
Opened 2018-04-01 21:21 UTC by YuliaLitvinenko

2018-04-03 07:53 UTC, Afelua requested changes

2018-04-03 07:53 UTC, Afelua commented on style.css
Проверить ширину блока .main-info-container, выглядит, будто должно быть под 1115px
<img width="1202" alt="screen shot 2018-04-03 at 10 45 38" src="https://user-images.githubusercontent.com/8777546/38236233-301cf822-372c-11e8-9a55-12bc34b6c9d7.png">

2018-04-03 07:53 UTC, Afelua commented on index.html
> +          <div class="article-1-highlighting" height="320px">
По макету 394px, проверить по всем

2018-04-03 07:53 UTC, Afelua commented on style.css
Для .article и .footer-links аналогично

2018-04-03 07:53 UTC, Afelua commented on style.css
.article-subtitle - здесь шрифт 16px 
<img width="347" alt="screen shot 2018-04-03 at 10 48 23" src="https://user-images.githubusercontent.com/8777546/38236349-8e275584-372c-11e8-88a9-185e7d687250.png">

2018-04-03 07:53 UTC, Afelua commented on style.css
>  	padding: 10px 20px;
Задать актуальные padding для формы и кнопки. Также здесь 14px размер шрифта

<img width="785" alt="screen shot 2018-04-03 at 10 49 46" src="https://user-images.githubusercontent.com/8777546/38236415-c0281960-372c-11e8-94b4-ff4217b7e292.png">

2018-04-03 07:53 UTC, Afelua commented on style.css
>  .footer-menu-element-fb {
Проверить ширину и высоту иконок, по макету они под 
<img width="521" alt="screen shot 2018-04-03 at 10 52 23" src="https://user-images.githubusercontent.com/8777546/38236533-2541f5dc-372d-11e8-813a-b7391332fd23.png">
50px

2018-04-07 20:45 UTC, YuliaLitvinenko commented on style.css
Поправила! В футере оставила максимальную ширину несколько меньше, чтобы было похоже на макет.

2018-04-07 20:46 UTC, YuliaLitvinenko commented on index.html
> +          <div class="article-1-highlighting" height="320px">
Готово!

2018-04-07 20:46 UTC, YuliaLitvinenko commented on style.css
Поправила)

2018-04-07 20:46 UTC, YuliaLitvinenko commented on style.css
>  	padding: 10px 20px;
Готово)

2018-04-07 20:46 UTC, YuliaLitvinenko commented on style.css
>  .footer-menu-element-fb {
Увеличила)

2018-04-10 19:44 UTC, merged